language: python
services:
  - postgresql
  - mysql
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_script:
  - psql -c 'create database hydra_base_test;' -U postgres
  - mysql -e 'CREATE DATABASE hydra_base_test;'

install:
  - pip install -e .

script:
  - pytest tests --db-backend=sqlite
  - pytest tests --db-backend=mysql
  - pytest tests --db-backend=postgres