language: python
services:
  - postgresql
  - mysql
python:
  - "2.7"
  - "3.6"
env:
- DB=sqlite
- DB=postgres
- DB=mysql

before_script:
  - |
    set -e
    if [ "$DB" -eq "postgres" ]; then
      psql -c 'create database hydra_base_test;' -U postgres
    fi
    if [ "$DB" -eq "mysql" ]; then
      mysql -e 'CREATE DATABASE hydra_base_test;'
    fi

install:
  - pip install -e .

script:
  - pytest tests --db-backend=$DB
